<a href="https://colab.research.google.com/github/SankritaPatel/Notes/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy - Numerical python

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [4]:
a = np.array(l)

In [5]:
type(a)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
a = [2,3,4]

In [9]:
np.asanyarray(a)

array([2, 3, 4])

In [10]:
b = np.mat(l)

In [11]:
b

matrix([[1, 2, 3, 4]])

In [12]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [13]:
a = np.array(l)

In [14]:
a

array([1, 2, 3, 4])

In [15]:
c = a

In [16]:
c

array([1, 2, 3, 4])

In [17]:
a

array([1, 2, 3, 4])

In [18]:
c[0]

1

In [19]:
c[0] = 100

In [20]:
c

array([100,   2,   3,   4])

In [21]:
a

array([100,   2,   3,   4])

In [22]:
#THis is called shallow copy.

In [23]:
d = np.copy(a)

In [24]:
d

array([100,   2,   3,   4])

In [25]:
a[1] = 400

In [26]:
a

array([100, 400,   3,   4])

In [27]:
d

array([100,   2,   3,   4])

In [28]:
#Deep copy

In [29]:
np.fromfunction(lambda i, j:i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i, j:i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [31]:
iterable = (i*i for i in range(5))

In [32]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [33]:
np.fromstring('234 345', sep = ' ')

array([234., 345.])

In [34]:
np.fromstring('4,5', sep=',')

array([4., 5.])

In [35]:
l = [2,3,4,5,6]

In [36]:
arr = np.array(l)

In [37]:
arr

array([2, 3, 4, 5, 6])

In [38]:
arr.ndim

1

In [39]:
arr2 = np.array([[1,2,3], [4,5,6]])

In [40]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr2.ndim

2

In [42]:
arr.size

5

In [43]:
arr2.size

6

In [44]:
arr.shape

(5,)

In [45]:
arr2.shape

(2, 3)

In [47]:
arr.dtype

dtype('int64')

In [48]:
arr2.dtype

dtype('int64')

In [49]:
ar22 = np.array([(1.4, 45, 45),(23, 45,66)])

In [50]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [52]:
ar22.dtype

dtype('float64')

In [53]:
list(range(5))

[0, 1, 2, 3, 4]

In [54]:
list(range(0.1, 5))

TypeError: ignored

In [55]:
np.arange(2.3, 5.6)

array([2.3, 3.3, 4.3, 5.3])

In [56]:
np.arange(2.3, 5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [57]:
list(np.arange(2.3, 5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [58]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [61]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [62]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [65]:
np.ones(4)

array([1., 1., 1., 1.])

In [67]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [69]:
on = np.ones((2,3,2))

In [70]:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [71]:
on*4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [73]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [74]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [76]:
np.logspace(2,5,10, base =2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [79]:
arr = np.random.randn(3,4)

In [78]:
import pandas as pd

In [80]:
pd.DataFrame(arr)

0         1         2         3
0  1.160577  0.301780 -0.830266 -0.762529
1  0.116239  0.767914  0.438101  0.722787
2  0.223033  0.901690 -1.381442  0.915886

In [82]:
np.random.rand(3,4)

array([[0.86045994, 0.46619318, 0.79899796, 0.1616016 ],
       [0.83835694, 0.39255716, 0.76535872, 0.83179412],
       [0.69095314, 0.11365296, 0.51273478, 0.12398554]])

In [84]:
pd.DataFrame(np.random.randint(1,110,(300,400)))

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     86   65   58   98   11    4   89   33   16   68  ...   99   21   42   
1     93   24   76    4   52   32   99   51   24    1  ...   84  107  108   
2     33   46   74   50   43   82   94    3   64    2  ...   45   13   75   
3     92   32   14   64   82   61   14   67    7   96  ...   62   71  109   
4     30   51   84   59   91   23   62  104   73   64  ...   22  103   20   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   24   60   84    3   25   51   58   86   50   87  ...   91   12   60   
296   41   31   33   60  102   61   47   89    4  101  ...   93   59   47   
297   35   86   90   30   93   89   83   22   33    7  ...   41   68  109   
298   93   14   85    8    8   80   88   29   51    9  ...   77   29   13   
299   83   19   80  108   70   22   38   53   80   45  ...   20  109   22   

     393  394  395  396  397  398  399  
0     67   13   75  106   99   27  106  
1     39   96   45   43   35   74   80  
2     39   92   28   35   52  103    4  
3     43   88   80   71   55   42   95  
4     83   58   57   69   69   89   95  
..   ...  ...  ...  ...  ...  ...  ...  
295   58   88   49  102   49   90   93  
296   98   72   55   83   83  107   58  
297   33   39   12   48   94   21   98  
298    4   67  107  103   48   97   57  
299   59   20   33   53   68   27  108  

[300 rows x 400 columns]

In [85]:
arr = np.random.rand(3,4)

In [86]:
arr.reshape(6,2)

array([[0.24369346, 0.74304763],
       [0.46285336, 0.63242584],
       [0.33142   , 0.91640372],
       [0.35602357, 0.9161795 ],
       [0.51471235, 0.40483625],
       [0.45261597, 0.86892075]])

In [87]:
arr1 = arr.reshape(6, -134)

In [88]:
arr1

array([[0.24369346, 0.74304763],
       [0.46285336, 0.63242584],
       [0.33142   , 0.91640372],
       [0.35602357, 0.9161795 ],
       [0.51471235, 0.40483625],
       [0.45261597, 0.86892075]])

In [89]:
arr1[1][1]

0.6324258388104431

In [90]:
arr1[2:5,1]

array([0.91640372, 0.9161795 , 0.40483625])

In [91]:
arr = np.random.randint(1,100, (5,5))

In [92]:
arr

array([[22, 79, 24, 96, 76],
       [ 7, 71, 58, 59, 41],
       [37, 27, 55, 90, 23],
       [51, 27, 18, 48, 39],
       [25, 75, 35, 15, 77]])

In [93]:
arr>50

array([[False,  True, False,  True,  True],
       [False,  True,  True,  True, False],
       [False, False,  True,  True, False],
       [ True, False, False, False, False],
       [False,  True, False, False,  True]])

In [94]:
arr[arr>50]

array([79, 96, 76, 71, 58, 59, 55, 90, 51, 75, 77])

In [95]:
arr[2:4,[1,2]]

array([[27, 55],
       [27, 18]])

In [97]:
arr[0][0] = 5000

In [98]:
arr

array([[5000,   79,   24,   96,   76],
       [   7,   71,   58,   59,   41],
       [  37,   27,   55,   90,   23],
       [  51,   27,   18,   48,   39],
       [  25,   75,   35,   15,   77]])

In [101]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [102]:
arr1

array([[1, 1, 1],
       [1, 2, 1],
       [2, 2, 1]])

In [103]:
arr2

array([[1, 2, 2],
       [2, 1, 2],
       [2, 1, 1]])

In [104]:
arr1+arr2

array([[2, 3, 3],
       [3, 3, 3],
       [4, 3, 2]])

In [105]:
arr1-arr2

array([[ 0, -1, -1],
       [-1,  1, -1],
       [ 0,  1,  0]])

In [106]:
arr1/arr2

array([[1. , 0.5, 0.5],
       [0.5, 2. , 0.5],
       [1. , 2. , 1. ]])

In [107]:
arr1*arr2

array([[1, 2, 2],
       [2, 2, 2],
       [4, 2, 1]])

In [108]:
arr1@arr2

array([[5, 4, 5],
       [7, 5, 7],
       [8, 7, 9]])

In [110]:
arr1+100

array([[101, 101, 101],
       [101, 102, 101],
       [102, 102, 101]])

In [111]:
arr1**2

array([[1, 1, 1],
       [1, 4, 1],
       [4, 4, 1]])

In [113]:
#Numpy BroadCasting
arr = np.zeros((4,4))

In [114]:
row = np.array([1,2,3,4])

In [115]:
row

array([1, 2, 3, 4])

In [116]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [117]:
row.T

array([1, 2, 3, 4])

In [118]:
col = np.array([[1,2,3,4]])

In [120]:
col.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [121]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [123]:
arr1 = np.random.randint(1,4,(3,4))

In [124]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.73205081, 1.41421356],
       [1.73205081, 1.        , 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.41421356, 1.73205081]])

In [125]:
np.exp(arr1)

array([[ 2.71828183,  2.71828183, 20.08553692,  7.3890561 ],
       [20.08553692,  2.71828183,  7.3890561 ,  2.71828183],
       [ 2.71828183,  7.3890561 ,  7.3890561 , 20.08553692]])

In [126]:
np.log10(arr1)

array([[0.        , 0.        , 0.47712125, 0.30103   ],
       [0.47712125, 0.        , 0.30103   , 0.        ],
       [0.        , 0.30103   , 0.30103   , 0.47712125]])

In [127]:
arr1 = np.random.randint(1,10,(3,4))

In [128]:
arr1.reshape(6,2)

array([[2, 8],
       [5, 9],
       [6, 8],
       [3, 5],
       [4, 1],
       [5, 4]])

In [129]:
arr1.reshape(2,6)

array([[2, 8, 5, 9, 6, 8],
       [3, 5, 4, 1, 5, 4]])

In [130]:
arr1.reshape(2,7)

ValueError: ignored

In [131]:
arr1.T

array([[2, 6, 4],
       [8, 8, 1],
       [5, 3, 5],
       [9, 5, 4]])

In [132]:
arr1.flatten()

array([2, 8, 5, 9, 6, 8, 3, 5, 4, 1, 5, 4])

In [133]:
arr1 = np.array([1,2,3,3,4])

In [134]:
arr1.ndim

1

In [136]:
np.expand_dims(arr1, axis=0)

array([[1, 2, 3, 3, 4]])

In [137]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [138]:
data = np.array([[1], [2], [3]])

In [139]:
data

array([[1],
       [2],
       [3]])

In [140]:
np.squeeze(data)

array([1, 2, 3])

In [141]:
arr1

array([1, 2, 3, 3, 4])

In [142]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [143]:
np.roll(arr1, 2)

array([3, 4, 1, 2, 3])

In [144]:
arr1

array([1, 2, 3, 3, 4])

In [145]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [146]:
#Numpy binary operator

In [147]:
arr1 = np.random.randint(1, 10, (3, 4))

In [148]:
arr2 = np.random.randint(1,10,(3,4))

In [149]:
arr1%arr2

array([[3, 0, 1, 1],
       [2, 1, 1, 4],
       [3, 1, 1, 0]])

In [150]:
arr1**arr2

array([[531441,     64,      1,      1],
       [   512,     49, 117649,   1024],
       [    81,     81,    343,   4096]])

In [151]:
arr1&arr2

array([[0, 0, 1, 1],
       [0, 2, 6, 4],
       [0, 0, 3, 0]])

In [152]:
~arr1

array([[-10,  -9,  -2,  -2],
       [ -9,  -8,  -8,  -5],
       [ -4, -10,  -8,  -9]])

In [153]:
arr1|arr2

array([[15, 10,  3,  7],
       [11,  7,  7,  5],
       [ 7, 11,  7, 12]])

In [155]:
arr1>arr2

array([[ True,  True, False, False],
       [ True,  True,  True, False],
       [False,  True,  True,  True]])

In [156]:
#Numpy - string function

In [157]:
arr = np.array(['sudh', 'kumar'])

In [158]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [159]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [160]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [161]:
#Numpy mathematical function

In [162]:
arr1

array([[9, 8, 1, 1],
       [8, 7, 7, 4],
       [3, 9, 7, 8]])

In [163]:
np.sin(arr1)

array([[ 0.41211849,  0.98935825,  0.84147098,  0.84147098],
       [ 0.98935825,  0.6569866 ,  0.6569866 , -0.7568025 ],
       [ 0.14112001,  0.41211849,  0.6569866 ,  0.98935825]])

In [164]:
np.cos(arr1)

array([[-0.91113026, -0.14550003,  0.54030231,  0.54030231],
       [-0.14550003,  0.75390225,  0.75390225, -0.65364362],
       [-0.9899925 , -0.91113026,  0.75390225, -0.14550003]])

In [166]:
np.tan(arr1)

array([[-0.45231566, -6.79971146,  1.55740772,  1.55740772],
       [-6.79971146,  0.87144798,  0.87144798,  1.15782128],
       [-0.14254654, -0.45231566,  0.87144798, -6.79971146]])

In [167]:
np.tanh(arr1)

array([[0.99999997, 0.99999977, 0.76159416, 0.76159416],
       [0.99999977, 0.99999834, 0.99999834, 0.9993293 ],
       [0.99505475, 0.99999997, 0.99999834, 0.99999977]])

In [168]:
np.exp(arr1)

array([[8.10308393e+03, 2.98095799e+03, 2.71828183e+00, 2.71828183e+00],
       [2.98095799e+03, 1.09663316e+03, 1.09663316e+03, 5.45981500e+01],
       [2.00855369e+01, 8.10308393e+03, 1.09663316e+03, 2.98095799e+03]])

In [169]:
np.power(arr1, 2)

array([[81, 64,  1,  1],
       [64, 49, 49, 16],
       [ 9, 81, 49, 64]])

In [170]:
np.mean(arr1)

6.0

In [171]:
np.median(arr1)

7.0

In [173]:
np.std(arr1)

2.8284271247461903

In [174]:
np.var(arr1)

8.0

In [175]:
np.min(arr1)

1

In [176]:
np.max(arr1)

9

In [177]:
#Sort, search and counting function

In [178]:
arr = np.array([4,3,4,6,72,3,3,455,5,6,6])

In [179]:
arr

array([  4,   3,   4,   6,  72,   3,   3, 455,   5,   6,   6])

In [180]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   6,   6,   6,  72, 455])

In [181]:
np.searchsorted(arr, 34)

11

In [182]:
arr1 = np.array([0,345,454,0,0,0,0,0])

In [183]:
np.count_nonzero(arr1)

2

In [184]:
arr

array([  4,   3,   4,   6,  72,   3,   3, 455,   5,   6,   6])

In [185]:
np.where(arr>6)

(array([4, 7]),)

In [187]:
np.extract(arr>6,arr)

array([ 72, 455])

In [188]:
#Numy byte swapping

In [189]:
arr.byteswap()

array([  288230376151711744,   216172782113783808,   288230376151711744,
         432345564227567616,  5188146770730811392,   216172782113783808,
         216172782113783808, -4107001385185181696,   360287970189639680,
         432345564227567616,   432345564227567616])

In [190]:
#Numpy - Copies and Views

In [191]:
a = np.copy(arr)

In [192]:
b = arr.view() #Shallow copy

In [193]:
b

array([  4,   3,   4,   6,  72,   3,   3, 455,   5,   6,   6])

In [194]:
b[0] = 67

In [195]:
b

array([ 67,   3,   4,   6,  72,   3,   3, 455,   5,   6,   6])

In [196]:
arr

array([ 67,   3,   4,   6,  72,   3,   3, 455,   5,   6,   6])

In [197]:
#Numpy - Matrix libary

In [198]:
import numpy.matlib as nm

In [200]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [202]:
nm.ones(5)

matrix([[1., 1., 1., 1., 1.]])

In [203]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [204]:
#Numpy - Linear Algebra

In [205]:
arr1 = np.random.randint([[2,3],[4,5]])
arr2 = np.random.randint([[5,3],[2,5]])

In [206]:
np.dot(arr1, arr2)

array([[0, 4],
       [4, 8]])

In [207]:
arr1@arr2

array([[0, 4],
       [4, 8]])